lr_actor: 0.0003 # learning rate for actor network
lr_critic: 0.001 # learning rate for critic network
K_epochs: 80   # update policy for K epochs in one PPO update
eps_clip: 0.2  # clip parameter for PPO
gamma: 0.99  # discount factor
state_dict: [3, 64, 64]

