train:
  _target_: envs.make_multi_agent_carla
  id: 0
  size: 64
  max_episode_steps: 20000
  noop_max: 30
  frame_skip: 2
  done_on_life_loss: True
  clip_reward: False
  n_agents: 10

test:
  _target_: ${..train._target_}
  id: ${..train.id}
  size: ${..train.size}
  max_episode_steps: 108000
  noop_max: 1
  frame_skip: ${..train.frame_skip}
  done_on_life_loss: False
  clip_reward: False

keymap: atari/${.train.id}
